#!/bin/bash
output=""
reprint () {
	 clear
	 figlet Welcome Ayushmaan
	 echo -e "$output"
}

reprint

#Wait for Internet
echo "Waiting for wifi"
until ping -c 1 archlinux.org | grep "ttl="; do sleep 1; done
echo "Connected to Internet"; echo

# Set Time
if [ $(timedatectl show | grep NTPSync) != $(echo -e NTPSynchronized=yes) ]
then	
	echo "Sync Time"
	sudo timedatectl set-ntp true
	output="Synced Time\n\n"
	echo; echo; sleep 1
fi

# reprint

# This script updates all pacman packages(no flatpak or snap packages on computer)
echo "Updating Packages: " 
sudo pacman -Sy | tee /var/log/scripts/AutoUpdate 
output+="Pacman Updated: $(pacman -Qu) \n"
sudo pacman -Syu # Update packages
sudo paccache -rvk2 # Clear cache after 2 versions of packages
sudo paccache -rvu # Clear cache of uninstalled packages
#sudo snap refresh
# reprint
sudo flatpak update 
sudo npm update 
sudo mamba update conda 
yay -Syuqaw --ignore miniconda3 --answerclean All --answerdiff None --answeredit None 

echo "Need to figure out pycache for yay"
#echo; figlet "spotify-tui"
#cd /home/ayushmaan/Applications/spotify-tui
#cargo install spotify-tui

echo "Back up package lists"
pacman -Q > /home/ayushmaan/Backups/pacman/package_all.backup
conda env export -n base > /home/ayushmaan/Backups/conda_envs/base_environment.yml
conda env export -n plain > /home/ayushmaan/Backups/conda_envs/plain_environment.yml
conda env export -n ml > /home/ayushmaan/Backups/conda_envs/ml_environment.yml
conda env export -n webdev > /home/ayushmaan/Backups/conda_envs/webdev_environment.yml
conda env export -n sslresearch > /home/ayushmaan/Backups/conda_envs/sslresearch_environment.yml
conda env export -n physics > /home/ayushmaan/Backups/conda_envs/physics_environment.yml

echo; echo "dwm status"
cd /home/ayushmaan/dwm
git status -sb

echo; echo "st status"
cd /home/ayushmaan/st
git status -sb

echo; echo "dmenu status"
cd /home/ayushmaan/dmenu
git status -sb

echo; echo "dwmstatus status"
cd /home/ayushmaan/dwmstatus
git status -sb

figlet "Finished Startup"
sleep 6

kill -9 $PPID
