#!/bin/bash

HEIGHT=30
WIDTH=40
CHOICE_HEIGHT=12
BACKTITLE="Made by Ayushmaan"
TITLE="Latex Folder"
MENU="Choose one of the following options:"

OPTIONS=(1 "Physics 5a"
	 2 "Math 53"
  	 3 "Other")
CHOICE=$(dialog --clear --backtitle "$BACKTITLE"  --title "$TITLE" --menu "$MENU" $HEIGHT $WIDTH $CHOICE_HEIGHT  "${OPTIONS[@]}" 2>&1 >/dev/tty)

clear
case "$CHOICE" in
	1)
	folder="Physics 5A";;
	2)
	folder="Math 53";;
	3)
	folder="Other";;
	*)
	echo "Not Valid Choice"
	;;
esac

echo Enter filename of Latex Document
read filename

file="/home/ayushmaan/Documents/Latex/${folder}" 

pdflatex -output-directory="${file}/Output" "${file}/${filename}.tex" 
evince "${file}/Output/${filename}.pdf"
